### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jurca** [TehShrike/key-master#8]
Hello,

would you be willing to support TypeScript ecosystem? There are various options, however, I think it would be best for future maintainability to port the code to TypeScript instead of adding separate type declaration files.

I am willing to do all the work myself and send a pull request.

Would that be OK with you, or would you rather go for a different option?

**Comment by TehShrike** [comment]
I'm open to having type definitions in this repo, as long as there are automated tests for them.

Assuming that the underlying code doesn't change, and TypeScript annotations can be added to the existing code, I'm open to moving the codebase to TS.

**Comment by jurca** [comment]
> Assuming that the underlying code doesn't change

That's the plan, I don't want to cause you any trouble. I might also add some unit tests while I'm at it, if that's OK with you.

**Comment by jurca** [comment]
I have prepared the new code, you may already check it here: https://github.com/jurca/key-master

Unfortunately, I encountered a possible unintended issue. By default the `set` method returns the underlying native map (the return value of the underlying storage's `set` method), which could be potentially confusing to the user of the library.

I would like to suggest changing the implementation so that the `set` method either returns the wrapper provided by `key-master`, or returns `void`. Which option would you prefer?

**Comment by jurca** [comment]
@TehShrike I would prefer the first option - change `set` so that it returns the wrapper provided by `key-master`. Is that OK with you?

**Comment by TehShrike** [comment]
`set`'s return value is undefined as far as `key-master` is concerned.  If you pass in [your own implementation](https://github.com/TehShrike/key-master#using-a-plain-old-object-as-a-map), its `set` isn't expected to return anything.  The types should reflect that.

**Comment by jurca** [comment]
Thanks for the answer. I've updated the code and created a pull request: https://github.com/TehShrike/key-master/pull/9
